version: "3.9"

services:
  admin:
    image: vineeshw1994/swarm-blog-admin:latest
    ports:
      - "4002:4002"
    env_file:
      - .env
    deploy:
      replicas: 1
      restart_policy:
        condition: always
